import base64

import utils
import re
import os
import requests
from bs4 import BeautifulSoup
import urllib.request

# http://dcimg.awalker.jp/img1.php?id=nVUBq7MT2ntqBgwlHX6nRbrRMeYVutr4K5nCGIuO4vv9JhSeslEV9A8m4PN1T7bFulHJ7eaZs2GEpjeZp7dTnIfWrl1I8tUn9AHoHIQR0mZAUHj9QTn4Y4Ha7ZvTZOpTKdsdhY3PC3934rIXoaGfYB3GVnfrLNnbH7zfyxMjxoM3MsGIKpWbbYy7XbIvBNXUP0xGBlI6
# http://dcimg.awalker.jp/i/HLq5KFoTQ5uH5zlXr52sfdmriDj2gBP1eFKIiiOlcseL24MBzFKAnNPTINbwNEH86QBi2dubQO4bs9ZoCjlOWeGfRQt4MreYlitCTCJcTIrFQalOHVrqRwynLSTXMHT1iRdTCAFqtW2m11M79P6aJmSbHrdGYlOqvCbInZUVoMVvksufeEmnxdqsXydpRaCDrSh40JLW

if __name__ == '__main__':
    url = 'http://dcimg.awalker.jp/v/HLq5KFoTQ5uH5zlXr52sfdmriDj2gBP1eFKIiiOlcseL24MBzFKAnNPTINbwNEH86QBi2dubQO4bs9ZoCjlOWeGfRQt4MreYlitCTCJcTIrFQalOHVrqRwynLSTXMHT1iRdTCAFqtW2m11M79P6aJmSbHrdGYlOqvCbInZUVoMVvksufeEmnxdqsXydpRaCDrSh40JLW'

    path = utils.get_dc_path(url)
    utils.download_dcimg(path, url)